<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="arch" nsURI="http://www.example.org/arch" nsPrefix="arch">
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1" eType="#//Port"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deploymentnode" eType="#//ExecutionEnvironment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="criticalLevel" eType="#//CriticalLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityCharacters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DesignModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" upperBound="-1"
        eType="#//Connector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="archstyle" upperBound="-1"
        eType="#//ArchStyle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verifyProperty" upperBound="-1"
        eType="#//VerificationProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="host" upperBound="-1" eType="#//Device"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" upperBound="-1" eType="#//CommunicationLink"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" upperBound="-1" eType="#//Role"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectortype" eType="#//ConnectorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="communicationlink" upperBound="-1"
        eType="#//CommunicationLink"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityCharacters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" upperBound="-1" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="insecure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roletype" eType="#//RoleType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextRoleExpr" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operatorExpr" eType="#//ExprOperator"
        defaultValueLiteral="COUPLING"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" eType="#//Connector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Channel" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bind" eType="#//Channel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//Event" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="porttype" eType="#//PortType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectorType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roletype" upperBound="-1"
        eType="#//RoleType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eaConnector" eType="#//ConnectorType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="porttype" upperBound="-1"
        eType="#//PortType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectortype" upperBound="-1"
        eType="#//ConnectorType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componenttype" upperBound="-1"
        eType="#//ComponentType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExprOperator">
    <eLiterals name="PARALLEL"/>
    <eLiterals name="COUPLING" value="1"/>
    <eLiterals name="INTERLEAVE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LTLOperator">
    <eLiterals name="ALWAYS"/>
    <eLiterals name="EVENTUALLY" value="1"/>
    <eLiterals name="NONE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviourProperty" eSuperTypes="#//VerificationProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ltlexpr" upperBound="-1"
        eType="#//LTLExpr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counterExample" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visitedStates" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verifyTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//BehaviourPropType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testport" eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceExample" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LTLExpr" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//LTLOperator"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextExpr" eType="#//LTLExpr"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//BehaviourProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LTLNestedExpr" eSuperTypes="#//LTLExpr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" upperBound="-1" eType="#//LTLExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LTLRegularExpr" eSuperTypes="#//LTLExpr"/>
  <eClassifiers xsi:type="ecore:EEnum" name="BehaviourPropType">
    <eLiterals name="LTL"/>
    <eLiterals name="CircularFree" value="1" literal="CD"/>
    <eLiterals name="DecompositionFree" value="2" literal="FD"/>
    <eLiterals name="PoltergeistFree" value="3" literal="PG"/>
    <eLiterals name="AmbiguousInterfaceFree" value="4" literal="AI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VerificationProperty" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//DesignModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralProperty" eSuperTypes="#//VerificationProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="netAccessType" eType="#//NetAccessType"
        defaultValueLiteral="PRIVATE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" upperBound="-1" eType="#//ExecutionEnvironment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostType" eType="#//HostType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NodeType">
    <eLiterals name="DOCKER_CONTAINER" value="1" literal="DOCKER_CONTAINER"/>
    <eLiterals name="APPLICATION_CONTAINER" value="2"/>
    <eLiterals name="FILE_SYSTEM" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionEnvironment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//NodeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1" eType="#//CommunicationPort"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HostType">
    <eLiterals name="VIRTUAL_MACHINE" literal="VIRTUAL_MACHINE"/>
    <eLiterals name="DEDICATED_SERVER" value="1"/>
    <eLiterals name="CLOUD_PLATFORM" value="2"/>
    <eLiterals name="MOBILE_PHONE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LinkType">
    <eLiterals name="HTTP"/>
    <eLiterals name="HTTPS" value="1"/>
    <eLiterals name="FTPS" value="2"/>
    <eLiterals name="FTP" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationLink">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkType" eType="#//LinkType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="networkType" eType="#//NetworkType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//CommunicationPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//CommunicationPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NetAccessType">
    <eLiterals name="PRIVATE"/>
    <eLiterals name="PUBLIC" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NetworkType">
    <eLiterals name="INTRANET"/>
    <eLiterals name="INTERNET" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationPort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="#//ExecutionEnvironment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namedport" upperBound="-1"
        eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasFirewall" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasAuthentication" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasAuthorization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasInputSanitization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CriticalLevel">
    <eLiterals name="VeryLow" literal="Very Low"/>
    <eLiterals name="Low" value="1"/>
    <eLiterals name="High" value="2"/>
    <eLiterals name="VeryHigh" value="3"/>
  </eClassifiers>
</ecore:EPackage>
